
[window]
opacity = 1.0
startup_mode = "Maximized"
decorations = "None"

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Never" }
blink_interval = 500
blink_timeout = 0

[general]
live_config_reload = true
working_directory = "~"
import = [
    "./themes/alacritty-theme/themes/github_dark_default.toml"
]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 10.0

